import fs from "node:fs"
import path from "node:path"
import { scanApiRoutes } from "@metaving/plugin-hono"
import { scanPages } from "./routes.js"

const ensureDir = (dir: string) => {
  fs.mkdirSync(dir, { recursive: true })
}

const writeFile = (filePath: string, content: string) => {
  ensureDir(path.dirname(filePath))
  fs.writeFileSync(filePath, content, "utf8")
}

const normalizeModulePath = (filePath: string) => filePath.split(path.sep).join("/")

export type MetavingGenerateOptions = {
  router?: {
    custom?: boolean
  }
}

const generateRoutesFile = (root: string) => {
  const pagesDir = path.join(root, "app/pages")
  const routes = scanPages(pagesDir)
  const routerFile = path.join(root, ".metaving/generated/router.ts")
  const entries = routes.map((route) => {
    const relativePath = path.relative(path.dirname(routerFile), route.filePath)
    const componentPath = normalizeModulePath(relativePath.startsWith(".") ? relativePath : `./${relativePath}`)
    return `  { path: "${route.path}", component: () => import("${componentPath}") }`
  })
  const header = "// Generated by metaving. Do not modify.\n"
  const content = `${header}const routes = [\n${entries.join(",\n")}\n]\n\nexport default routes\n`
  writeFile(routerFile, content)
}

const resolveRouterModule = (root: string, allowCustom: boolean) => {
  const customRouter = path.join(root, "app/router/index.ts")
  if (allowCustom && fs.existsSync(customRouter)) return "/app/router/index.ts"
  return "/.metaving/generated/router.ts"
}

const generateEntries = (root: string, options?: MetavingGenerateOptions) => {
  const generatedDir = path.join(root, ".metaving/generated")
  const routerModule = resolveRouterModule(root, options?.router?.custom === true)
  const header = "// Generated by metaving. Do not modify.\n"
  const entryClient = `${header}import { createApp } from "vue"\nimport { createRouter, createWebHistory } from "vue-router"\nimport routes from "${routerModule}"\nimport App from "/app/App.vue"\n\nconst app = createApp(App)\nconst router = createRouter({ history: createWebHistory(), routes })\napp.use(router)\nrouter.isReady().then(() => app.mount("#app"))\n`
  const entryServer = `${header}import { createSSRApp } from "vue"\nimport { createRouter, createMemoryHistory } from "vue-router"\nimport { renderToString } from "@vue/server-renderer"\nimport routes from "${routerModule}"\nimport App from "/app/App.vue"\n\nexport async function render(url: string) {\n  const app = createSSRApp(App)\n  const router = createRouter({ history: createMemoryHistory(), routes })\n  app.use(router)\n  await router.push(url)\n  await router.isReady()\n  const appHtml = await renderToString(app)\n  return appHtml\n}\n`
  writeFile(path.join(generatedDir, "entry-client.ts"), entryClient)
  writeFile(path.join(generatedDir, "entry-server.ts"), entryServer)
}

const generateServerEntry = (root: string) => {
  const generatedDir = path.join(root, ".metaving/generated")
  const serverEntry = path.join(root, "server/index.ts")
  const apiRoutes = scanApiRoutes(root)
  const imports = apiRoutes.map((route, index) => `import api${index} from "${route.modulePath}"`)
  const registerLines = apiRoutes.map((route, index) => {
    return `  const handler${index} = (api${index} as any)?.default ?? api${index}\n  if (handler${index} && typeof handler${index} === "object" && "routes" in handler${index}) {\n    app.route("${route.path}", handler${index})\n  } else if (typeof handler${index} === "function") {\n    app.all("${route.path}", handler${index})\n  }\n`
  })
  const serverImport = fs.existsSync(serverEntry) ? `import setupServer from "/server/index.ts"\n` : ""
  const serverSetup = fs.existsSync(serverEntry) ? `  if (typeof setupServer === "function") {\n    setupServer(app)\n  }\n` : ""
  const header = "// Generated by metaving. Do not modify.\n"
  const content = `${header}import { Hono } from "hono"\nimport { render as renderPage } from "./entry-server"\n${serverImport}${imports.join("\n")}\n\nexport const render = renderPage\n\nexport const setupApi = (app: Hono) => {\n${serverSetup}${registerLines.join("")}}\n`
  writeFile(path.join(generatedDir, "server-entry.ts"), content)
}

export const ensureMetavingFiles = (root: string, options?: MetavingGenerateOptions) => {
  generateRoutesFile(root)
  generateEntries(root, options)
  generateServerEntry(root)
}
